AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Thrive Church AWS Lambdas - Sermon Processing Pipeline (Transcription, Sermon, Podcast)

# =============================================================================
# PARAMETERS
# =============================================================================
Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment

# =============================================================================
# GLOBALS
# =============================================================================
Globals:
  Function:
    Runtime: python3.11
    Timeout: 60
    MemorySize: 256
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        # Shared secrets - all Lambdas need these
        MONGODB_SECRET_ARN: arn:aws:secretsmanager:us-east-2:349570132161:secret:thrive-api/database
        MONGODB_SECRET_KEY: MongoConnectionString
        OPENAI_SECRET_ARN: arn:aws:secretsmanager:us-east-2:349570132161:secret:thrive-api/openai
        OPENAI_SECRET_KEY: OpenAI_ChatCompletions_ApiKey

# =============================================================================
# RESOURCES
# =============================================================================
Resources:

  # ---------------------------------------------------------------------------
  # Lambda 1: Transcription Processor (Entry Point)
  # Downloads audio, transcribes with Whisper, invokes Sermon + Podcast Lambdas
  # ---------------------------------------------------------------------------
  TranscriptionProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub transcription-processor-${Environment}
      Description: Transcribes audio with Whisper API, then invokes Sermon and Podcast Lambdas
      Handler: handler.lambda_handler
      CodeUri: lambdas/transcription_processor/
      Timeout: 900  # 15 minutes max for long audio transcription
      MemorySize: 512  # More memory for audio download
      Role: arn:aws:iam::349570132161:role/podcast-lambda-execution-role
      # FFmpeg binary is bundled with the Lambda (downloaded during CI build)
      # Used to compress audio >25MB before sending to Whisper API (32kbps mono)
      Environment:
        Variables:
          S3_BUCKET: thrive-audio
          SERMON_LAMBDA_NAME: !Sub sermon-processor-${Environment}
          PODCAST_LAMBDA_NAME: !Sub podcast-rss-generator-${Environment}

  TranscriptionProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/transcription-processor-${Environment}
      RetentionInDays: 14

  # ---------------------------------------------------------------------------
  # Lambda 2: Sermon Processor
  # Generates summary, tags, waveform and updates SermonMessages
  # ---------------------------------------------------------------------------
  SermonProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub sermon-processor-${Environment}
      Description: Generates sermon summary, tags, waveform and updates SermonMessages
      Handler: handler.lambda_handler
      CodeUri: lambdas/sermon_processor/
      Timeout: 120
      MemorySize: 512  # More memory for waveform processing
      Role: arn:aws:iam::349570132161:role/podcast-lambda-execution-role
      # FFmpeg binary is bundled with the Lambda (downloaded during CI build)
      # Binary is at /var/task/bin/ffmpeg in the Lambda execution environment
      Environment:
        Variables:
          S3_BUCKET: thrive-audio

  SermonProcessorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/sermon-processor-${Environment}
      RetentionInDays: 14

  # ---------------------------------------------------------------------------
  # Lambda 3: Podcast RSS Generator
  # Generates podcast description, upserts to PodcastEpisodes, updates RSS XML
  # ---------------------------------------------------------------------------
  PodcastRssGeneratorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub podcast-rss-generator-${Environment}
      Description: Generates podcast description and updates RSS feed
      Handler: handler.lambda_handler
      CodeUri: lambdas/podcast_rss_generator/
      Timeout: 120
      MemorySize: 256
      Role: arn:aws:iam::349570132161:role/podcast-lambda-execution-role
      Environment:
        Variables:
          S3_BUCKET: thrive-audio
          S3_FEED_KEY: feed/rss.xml

  PodcastRssGeneratorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/podcast-rss-generator-${Environment}
      RetentionInDays: 14

# =============================================================================
# OUTPUTS
# =============================================================================
Outputs:
  # Transcription Lambda (Entry Point for API)
  TranscriptionProcessorArn:
    Description: Transcription Processor Lambda ARN
    Value: !GetAtt TranscriptionProcessorFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-TranscriptionProcessorArn

  TranscriptionProcessorName:
    Description: Transcription Processor Lambda Name (use this in ThriveChurchOfficialAPI)
    Value: !Ref TranscriptionProcessorFunction

  # Sermon Lambda
  SermonProcessorArn:
    Description: Sermon Processor Lambda ARN
    Value: !GetAtt SermonProcessorFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-SermonProcessorArn

  SermonProcessorName:
    Description: Sermon Processor Lambda Name
    Value: !Ref SermonProcessorFunction

  # Podcast Lambda
  PodcastRssGeneratorArn:
    Description: Podcast RSS Generator Lambda ARN
    Value: !GetAtt PodcastRssGeneratorFunction.Arn
    Export:
      Name: !Sub ${AWS::StackName}-PodcastRssGeneratorArn

  PodcastRssGeneratorName:
    Description: Podcast RSS Generator Lambda Name
    Value: !Ref PodcastRssGeneratorFunction

